<?php

function gsb_addthis_customization_addthis_markup_alter(&$markup) {

  $markup['counter'] = array(
    '#theme' => 'addthis_element',
    '#tag' => 'a',
    '#value' => '',
    '#attributes' => array(
      'class' => array('addthis_counter', 'addthis_bubble_style'),
    ),
    '#suffix' => '<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=gsbadmin"></script>',                
  );

}
