<?php

function gsb_addthis_customization_addthis_markup_alter(&$markup) {

  $module_path = drupal_get_path('module', 'gsb_addthis_customization');

  $markup['counter'] = array(
    '#theme' => 'addthis_element',
    '#tag' => 'a',
    '#value' => '',
    '#attributes' => array(
      'class' => array('addthis_counter', 'addthis_bubble_style'),
    ),
    '#prefix' => '<link rel="stylesheet" media="all" href="/' . $module_path . '/gsb_addthis_customization' . '.css" />',
    '#suffix' => '<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=gsbadmin"></script>',    
  );

}
